{ corePackages ? import ./core-haskell-packages.nix
} :

## The expanded list of all packages I want to have installed by
## default in each Haskell environment that I build, independent of
## the version of GHC.

hp: with hp; (corePackages hp) ++ [
  accelerate
  ad
  amazonka
  amazonka-ec2
  amazonka-route53
  amazonka-route53-domains
  amazonka-s3
  amazonka-sns
  amazonka-sqs
  auto
  autoexporter
  auto-update
  blaze-html
  blaze-markup
  blazeT
  bloodhound
  clay
  concurrent-machines
  conduit-combinators
  configurator
  configuration-tools
  constraints
  ether
  fgl
  formatting
  GraphSCC
  hakyll
  haxl
  haxl-amazonka
  hpio
  hex
  hnix
  hoopl
  hspec-webdriver
  hw-json
  hw-json-lens
  intervals
  ivory
  katip
  katip-elasticsearch
  lens-action
  lifted-async
  lifted-base
  linear
  linear-accelerate
  list-t
  llvm-general
  llvm-hs-pure
  lucid
  Lykah
  lzma
  machines
  machines-binary
  machines-directory
  machines-io
  machines-process
  memory
  numeric-extras
  parsec-free
  pipes-attoparsec
  pipes-errors
  pipes-group
  pipes-shell
  pipes-zlib
  process
  process-streaming
  reducers
  regex-applicative
  repline
  safecopy
  sbv
  shelly
  smtLib
  stm-containers
  tar
  tasty-hunit
  temporary
  thyme
  time-recurrence
  turtle
  uniplate
  uniqueid
  webdriver
  wires
  zlib-lens
]
